version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    groups:
      python-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    groups:
      node-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
